feat: fetch data from api at List componet
cyberhazard/adidas-shop-frontend pull request #12
Opened 2017-05-29 21:07 UTC by cyberhazard

2017-05-30 21:38 UTC, imevro requested changes

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +  fetchData(props) {
Да просто load

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +    const FETCH_URL = `http://localhost:3001/v1/products/${group}/${type}`;
Посмотри в сторону https://gist.github.com/evgenyrodionov/ade10ff8e3822610cc41d6cdbeeb4aa0

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +    const FETCH_URL = `http://localhost:3001/v1/products/${group}/${type}`;
Там же можно добавить r => r.json() сразу

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +                return (
Делай отступы

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +        <CutomGrid fluid>
Не трогай сетку, откуда это взялось

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +const makeImageLink = (id, fileName, height) =>
Вынеси в src/helpers.js например

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +    this.state = { products: '' };
Почему строка, если потом массив?

2017-05-30 21:38 UTC, evgenyrodionov commented on src/List/index.jsx
> +              this.state.products &&
А что конкретно ты тут проверяешь?

2017-06-04 21:57 UTC, cyberhazard commented
[Preview](https://build-weisuaroup.now.sh)

2017-06-04 22:22 UTC, imevro requested changes

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/Card/index.jsx
> +    <StyledLink to={to} sale={sale}>{price / 100 } $</StyledLink>
Вынеси цену в компонент `<Price currency=""></Price>` и сделай поддержку RUB EUR USD

Кстати по стандарту пишется как 500₽, €500, $500

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +  selectSize(size, selectedIndex) {
Императивный нейминг — нет

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +  selectSize(size, selectedIndex) {
Либо индекс либо сайз храни, в чем смысл обоими оперировать

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/index.jsx
> +export const StyledCol = styled(OriginalCol)`
Не трогай сетку сколько раз говорю

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/index.jsx
> +    this.state = { products: [], filtered: [] };
Не храни в стейте фильтрованные значения, лучше в рендере делай `products.filter().map()`

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/index.jsx
> +    const FETCH_URL = `https://erodionov-adidas-fake-api.now.sh/v1/products/${group}/${type}`;
Вынеси в `/src/api.js` и вообще сделай хелперы `get('/v1/products/${group}/${type}')`

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/index.jsx
> +    const FETCH_URL = `https://erodionov-adidas-fake-api.now.sh/v1/products/${group}/${type}`;
Незачем это тут хранить

2017-06-04 22:22 UTC, evgenyrodionov commented on src/List/index.jsx
> +      .reduce((allSizes, obj) => (allSizes.push(...obj.sizes), allSizes), []),
Без мутабельности плз

2017-06-05 21:18 UTC, imevro requested changes

2017-06-05 21:18 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +      this.setState({ selectedSize: '' });
null или undefined лучше пустой строки

2017-06-05 21:18 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +  selectSize(size) {
Императивный нейминг плох

2017-06-05 21:18 UTC, evgenyrodionov commented on src/List/index.jsx
> +export const StyledCol = styled(OriginalCol)`
не трогай сетку!!

2017-06-05 21:18 UTC, evgenyrodionov commented on src/List/index.jsx
> +  setFilter(filter = '') {
опять же императивный нейминг

2017-06-05 21:18 UTC, evgenyrodionov commented on src/List/index.jsx
> +    this.state = { products: [], filter: '' };
пустая строка плоха выше сказал

2017-06-06 13:12 UTC, imevro requested changes
Какая-то чехарда с типами: то null то пустая строка

Апи плох по дизайну

2017-06-06 13:12 UTC, evgenyrodionov commented on src/List/Card/Price.jsx
> +import React from 'react';
Кстати почему файл лежит в List/Card, если это дженерик компонент

2017-06-06 13:12 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +    if (size === this.state.selectedSize) {
Попробуй тут упростить

2017-06-06 13:12 UTC, evgenyrodionov commented on src/List/index.jsx
> +  handleFilterChange(filter = '') {
Почему пустая строка-то?

2017-06-06 13:12 UTC, evgenyrodionov commented on src/List/index.jsx
> +    get(group, type)
Поч `get(group, type)`? Что будет когда я захочу сделать запрос на `/v1/users/me`?

2017-06-06 13:12 UTC, evgenyrodionov commented on src/api.js
> +  fetch(`https://erodionov-adidas-fake-api.now.sh/v1/products/${group}/${type}/${id}`)
Нет нет нет

2017-06-06 23:15 UTC, imevro requested changes

2017-06-06 23:15 UTC, evgenyrodionov commented on src/List/Filter/index.jsx
> +    const filter = size === this.state.selectedSize ? null : size;
const selectedSize?

2017-06-07 13:07 UTC, merged