feat: added API to details page
cyberhazard/adidas-shop-frontend pull request #14
Opened 2017-06-04 21:57 UTC by cyberhazard

[Preview](https://build-weisuaroup.now.sh)

2017-06-04 22:33 UTC, imevro requested changes

2017-06-04 22:33 UTC, evgenyrodionov commented on src/Details/Carousel/index.jsx
> +      : { id: 0, fileName: '' };
Не стоит так делать

2017-06-04 22:33 UTC, evgenyrodionov commented on src/Details/index.jsx
> +    const FETCH_URL = `https://erodionov-adidas-fake-api.now.sh/v1/products/${group}/${type}/${id}`;
https://github.com/cyberhazard/adidas-shop-frontend/pull/12#discussion_r120022496

2017-06-06 13:24 UTC, imevro requested changes

2017-06-06 13:24 UTC, evgenyrodionov commented on src/Details/Carousel/index.jsx
> +    if (!this.props.images) return <div>Loading images</div>;
.length

2017-06-06 13:24 UTC, evgenyrodionov commented on src/api.js
> +export const get = (group, type, id = '') =>
я уже говорил про `GET /v1/users/me`

2017-06-06 15:44 UTC, cyberhazard commented on src/Details/Carousel/index.jsx
> +    if (!this.props.images) return <div>Loading images</div>;
так я же тут проверяю на существование this.props.images

2017-06-07 13:14 UTC, imevro approved these changes

2017-06-07 13:16 UTC, merged