Renew components
cyberhazard/adidas-shop-frontend pull request #3
Opened 2017-05-11 12:50 UTC by cyberhazard

Полностью переделал с нуля, включая верстку. Проверь пожалуйста.

2017-05-11 18:43 UTC, evgenyrodionov commented on package.json
> +  "name": "adidas-shop",
Отлично

2017-05-11 18:59 UTC, imevro requested changes
Очень хорошо, но иногда проблемы с неймингом. Плюс для boolean (true/false которые) пропсов лучше делай префикс is: isActive, isSelected, isOpen

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/BuyButton.js
> +const BuyButton = () => (
Засунь сразу в экспорт дефолт

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/Colors.js
> +    <Button color="#C5C5C5" />
Кайф

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/Description.js
> +
Что за лишние переносы тут

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/Previews/Item.js
> +const Item = ({img, selected, children}) => (
isActive, isSelected

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/Previews/index.js
> +const Previews = () => (
Делай сразу экспорт дефолт, к чему лишняя переменная

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/TopRight.js
> +import { Sale } from './../List/Card/styled';
Это лейбл

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/index.js
> +    <Order>
Не оч очевидно что такое ордер

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Details/index.js
> +      <Previews />
Лучше карусель

2017-05-11 18:59 UTC, evgenyrodionov commented on src/List/Card/index.js
> +  <CustomCol xs={12} sm={6} md={4} lg={3}>
Сетку лучше вынести за пределы карточки, чтобы карточку можно было переиспользовать в других местах. Обычно, например, существуют "похожие товары" и там тоже карточки

2017-05-11 18:59 UTC, evgenyrodionov commented on src/List/Card/index.js
> +  <CustomCol xs={12} sm={6} md={4} lg={3}>
а сетка при этом другая ай мин

2017-05-11 18:59 UTC, evgenyrodionov commented on src/List/index.js
> +import prodImg1 from './../assets/images/prod-1.png';
Через реквайр лучше

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.js
> +      <Text>Brands</Text>
Это же тоже ссылки

2017-05-11 18:59 UTC, evgenyrodionov commented on src/Sidebar/Search/index.js
> +    <SearchImage src={require('./search.svg')} alt=""/>
Icon

2017-05-11 18:59 UTC, evgenyrodionov commented on src/index.js
>  import App from './App';
Именованные импорты идут раньше неименованных

2017-05-12 00:17 UTC, cyberhazard commented
Внес правки

2017-05-12 10:08 UTC, imevro approved these changes

2017-05-12 10:09 UTC, merged