Dev
cyberhazard/adidas-shop-frontend pull request #4
Opened 2017-05-13 11:49 UTC by cyberhazard

Поправил ошибки eslint

2017-05-13 19:05 UTC, imevro requested changes
↓

2017-05-13 19:05 UTC, evgenyrodionov commented on src/App.jsx
> +  constructor(props) {
Это зачем

2017-05-13 19:05 UTC, evgenyrodionov commented on src/Details/Carousel/Item.jsx
> +import PropTypes from 'prop-types';
Можно выключить

2017-05-13 19:05 UTC, evgenyrodionov commented on src/Details/Carousel/Item.jsx
> +/* eslint-disable no-confusing-arrow */
Не-а, убирай это

2017-05-13 19:05 UTC, evgenyrodionov commented on src/Details/Carousel/Item.jsx
> +import PropTypes from 'prop-types';
В еслинтрс в смысле

2017-05-13 19:16 UTC, cyberhazard commented on src/App.jsx
> +  constructor(props) {
поправил

2017-05-13 19:16 UTC, cyberhazard commented on src/Details/Carousel/Item.jsx
> +/* eslint-disable no-confusing-arrow */
Убрал

2017-05-13 19:17 UTC, cyberhazard commented on src/Details/Carousel/Item.jsx
> +import PropTypes from 'prop-types';
Это можно оставить? Или все же убрать?

2017-05-13 19:17 UTC, cyberhazard commented
Поправил

2017-05-13 23:23 UTC, imevro requested changes
Не трогай еслинт правила без моего разрешения, убери проп-тайпс (и выключи еслинт-правило)

А так норм

2017-05-13 23:23 UTC, evgenyrodionov commented on package.json
> +    "prop-types": "^15.5.10",
Проп-тайпс можно выкинуть, а в еслинтс отключить проверку проптайпс, потому что у нас будет флоу.

2017-05-13 23:23 UTC, evgenyrodionov commented on src/Details/Colors.jsx
> +/* eslint-disable no-confusing-arrow */
Убери, нельзя выключать еслинт правила. Либо объясни зачем

2017-05-13 23:23 UTC, evgenyrodionov commented on src/List/index.jsx
> +/* eslint-disable no-mixed-operators */
Тоже

2017-05-13 23:23 UTC, evgenyrodionov commented on src/media.js
> +/* eslint-disable no-param-reassign */
и опять

2017-05-13 23:23 UTC, evgenyrodionov commented on src/media.js
>    lg: 1435,
Что за magic numbers

2017-05-14 10:10 UTC, imevro approved these changes
Да

2017-05-14 10:11 UTC, merged