Sidebar menu
cyberhazard/adidas-shop-frontend pull request #5
Opened 2017-05-21 10:47 UTC by cyberhazard

Правильно ли я понял смысл?

2017-05-21 17:46 UTC, imevro requested changes
А так да, норм. Но надо пофиксить. И вынеси MenuItem в отдельный файл

2017-05-21 17:46 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +        <MainLink to={this.props.to} isSelected={this.state.isActive}>{this.props.text}</MainLink>
text → title

2017-05-21 17:46 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +  render() {
Между методами отступ в одну строку

2017-05-21 23:01 UTC, cyberhazard commented
Внес правки. Но создал еще один ПЛ, где переделал принцип работы меню. Какой грамотнее/удобнее?

2017-05-22 18:27 UTC, imevro reviewed
↓

2017-05-22 18:27 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
>        <nav>
Можно убрать нав я думаю

2017-05-22 19:12 UTC, imevro requested changes
Пофикси

2017-05-22 19:12 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +    <MenuItem to="/" title="Football">
Почему ссылкой?

2017-05-22 19:12 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +    <MenuItem to="/" title="Football">
Это кнопка!

2017-05-22 19:12 UTC, evgenyrodionov commented on src/Sidebar/Menu/SubLink.jsx
> +    onClick={e => e.stopPropagation()}
И поэтому этот костыль не нужен

2017-05-22 19:12 UTC, imevro requested changes
И ещё

2017-05-22 19:12 UTC, evgenyrodionov commented on src/Sidebar/Menu/MenuItem.jsx
> +        <MainLink to={this.props.to} isSelected={this.state.isActive}>{this.props.title}</MainLink>
isSelected={isActive}? Странная консистентность

2017-05-22 19:12 UTC, evgenyrodionov commented on src/Sidebar/Menu/MenuItem.jsx
> +    this.setState({ isActive: !this.state.isActive });
https://medium.freecodecamp.com/functional-setstate-is-the-future-of-react-374f30401b6b
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-05-23 10:06 UTC, imevro requested changes

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/MenuItem.jsx
> +    this.state = { isSelected: false };
isOpened

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import MenuItem from './MenuItem';
Плохой нейминг

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import SubLink from './SubLink';
Зачем префикс саб?

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import MenuItem from './MenuItem';
зачем айтем?

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/MenuItem.jsx
> +import { MainLink, MenuItem as MenuItemStyled } from './styled';
Опять же, MenuItem? Зачем айтем?

2017-05-23 10:06 UTC, evgenyrodionov commented on src/Sidebar/Menu/MenuItem.jsx
> +import { MainLink, MenuItem as MenuItemStyled } from './styled';
MainLink? Это кнопка

2017-05-23 10:33 UTC, imevro approved these changes

2017-05-23 10:34 UTC, merged